version: '3.8'
services:
  postgres:
    image: postgis/postgis:15-3.3-alpine
    container_name: adatrack_postgres_local
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
    - 5432:5432
    volumes:
    - pgdata:/var/lib/postgresql/data
    healthcheck:
      test:
      - CMD-SHELL
      - pg_isready -U ${DB_USER} -d ${DB_NAME}
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7-alpine
    container_name: adatrack_redis_local
    command: redis-server --requirepass ""
    ports:
    - 6379:6379
    volumes:
    - redisdata:/data
    healthcheck:
      test:
      - CMD
      - redis-cli
      - ping
      interval: 5s
      timeout: 5s
      retries: 5
  nats:
    image: nats:2.10-alpine
    container_name: adatrack_nats_local
    command:
    - -js
    ports:
    - 4222:4222
    - 8222:8222
    volumes:
    - natsdata:/data
    healthcheck:
      test:
      - CMD
      - wget
      - -qO-
      - http://localhost:8222/healthz
      interval: 5s
      timeout: 5s
      retries: 5
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: adatrack_prometheus_local
    ports:
    - 9090:9090
    volumes:
    - ./deployments/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    - ./deployments/prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml
    - ./deployments/prometheus/targets:/etc/prometheus/targets
  grafana:
    image: grafana/grafana:10.0.3
    container_name: adatrack_grafana_local
    ports:
    - 3000:3000
    environment:
    - GF_SECURITY_ADMIN_PASSWORD=admin
    - GF_SECURITY_ALLOW_EMBEDDING=true
    - GF_AUTH_ANONYMOUS_ENABLED=true
    - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    volumes:
    - ./deployments/grafana/provisioning:/etc/grafana/provisioning
    - ./deployments/grafana/dashboards:/var/lib/grafana/dashboards
  minio:
    image: elestio/minio:latest
    container_name: adatrack_minio_local
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    ports:
    - 9000:9000
    - 9001:9001
    volumes:
    - miniodata:/data
    healthcheck:
      test:
      - CMD
      - curl
      - -f
      - http://localhost:9000/minio/health/live
      interval: 30s
      timeout: 20s
      retries: 3
  minio-setup:
    image: alpine:latest
    container_name: adatrack_minio_setup_local
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: '/bin/sh -c " /usr/bin/mc config host add myminio http://minio:9000
      ${S3_ACCESS_KEY} ${S3_SECRET_KEY}; /usr/bin/mc rm -r --force myminio/${S3_BUCKET_NAME}
      || true; /usr/bin/mc mb myminio/${S3_BUCKET_NAME} || true; /usr/bin/mc anonymous
      set public myminio/${S3_BUCKET_NAME}; exit 0; "

      '
  node-exporter:
    image: quay.io/prometheus/node-exporter:v1.6.0
    container_name: adatrack_node_exporter_local
    ports:
    - 9100:9100
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    container_name: adatrack_cadvisor_local
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter:v0.12.0
    container_name: adatrack_postgres_exporter_local
    environment:
      DATA_SOURCE_NAME: postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?sslmode=disable
    ports:
    - 9187:9187
    depends_on:
    - postgres
  alertmanager:
    image: quay.io/prometheus/alertmanager:v0.25.0
    container_name: adatrack_alertmanager_local
    ports:
    - 9093:9093
  postgres-replica:
    image: postgis/postgis:15-3.3-alpine
    container_name: adatrack_postgres_replica_local
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
    - 5532:5432
    depends_on:
      postgres:
        condition: service_healthy
    command: 'sh -c '' rm -rf /var/lib/postgresql/data/*; until pg_isready -h postgres
      -p 5432 -U ${DB_USER}; do sleep 2; done; PGPASSWORD="${DB_PASSWORD}" pg_basebackup
      -h postgres -U ${DB_USER} -D /var/lib/postgresql/data -Fp -Xs -P -R; chown -R
      postgres:postgres /var/lib/postgresql/data; chmod 700 /var/lib/postgresql/data;
      exec su postgres -c "postgres" ''

      '
  redis-replica:
    image: redis:7-alpine
    container_name: adatrack_redis_replica_local
    command: redis-server --replicaof redis 6379 --requirepass ""
    ports:
    - 6380:6379
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test:
      - CMD
      - redis-cli
      - ping
      interval: 5s
      timeout: 5s
      retries: 5
  api-vehicle:
    build:
      context: .
      dockerfile: ./services/api-vehicle/Dockerfile
    container_name: adatrack_api_vehicle_local
    env_file:
    - .env.local
    ports:
    - 8084:8084
    depends_on:
    - postgres
    - redis
    - nats
    restart: unless-stopped
volumes:
  pgdata: null
  redisdata: null
  natsdata: null
  miniodata: null
