-- ============================================================================
-- Migration: COMPANY 002 — vehicles (Enterprise-standard schema, PostgreSQL)
-- ============================================================================
-- Field enterprise & backward-compat sama persis dengan varian MySQL; hanya
-- penulisan tipe yang disesuaikan:
--   YEAR -> SMALLINT, DECIMAL -> NUMERIC, FLOAT -> DOUBLE PRECISION,
--   ENUM  -> TEXT + CHECK, TIMESTAMP ON UPDATE -> DEFAULT (versi PG).
-- ============================================================================

CREATE TABLE IF NOT EXISTS vehicles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    imei VARCHAR(30) NOT NULL,
    plate_number VARCHAR(20) NOT NULL,

    make VARCHAR(100),
    model VARCHAR(100),
    variant VARCHAR(100),
    year_of_manufacture SMALLINT,
    engine_number VARCHAR(100),
    chassis_number VARCHAR(100),
    color VARCHAR(50),
    fuel_type VARCHAR(20)
        CHECK (fuel_type IN ('petrol','diesel','electric','hybrid','CNG','LPG','hydrogen') OR fuel_type IS NULL),

    vehicle_category_code VARCHAR(20),
    vehicle_type_code     VARCHAR(30),

    vehicle_type VARCHAR(50),
    driver_name  VARCHAR(100),

    registration_number VARCHAR(50),
    registration_expiry DATE,
    insurance_number    VARCHAR(100),
    insurance_expiry    DATE,
    road_tax_expiry     DATE,
    inspection_expiry   DATE,

    gross_vehicle_weight DECIMAL(10,2),
    payload_capacity     DECIMAL(10,2),
    vehicle_length       DECIMAL(6,2),
    vehicle_width        DECIMAL(6,2),
    vehicle_height       DECIMAL(6,2),
    wheelbase            DECIMAL(6,2),

    driver_user_id BIGINT,

    device_model     VARCHAR(100),
    firmware_version VARCHAR(50),

    last_seen_at      TIMESTAMP,
    current_latitude  DECIMAL(10,8),
    current_longitude DECIMAL(11,8),
    current_speed     DOUBLE PRECISION,

    notes TEXT,
    status TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active','inactive','maintenance')),
    deleted_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_vehicles_imei UNIQUE (imei),
    CONSTRAINT uq_vehicles_chassis UNIQUE (chassis_number)
);
CREATE INDEX IF NOT EXISTS idx_veh_status ON vehicles (status);
CREATE INDEX IF NOT EXISTS idx_veh_type_code ON vehicles (vehicle_type_code);
CREATE INDEX IF NOT EXISTS idx_veh_cat_code ON vehicles (vehicle_category_code);
CREATE INDEX IF NOT EXISTS idx_veh_driver ON vehicles (driver_user_id);
CREATE INDEX IF NOT EXISTS idx_veh_last_seen ON vehicles (last_seen_at);
CREATE INDEX IF NOT EXISTS idx_veh_deleted ON vehicles (deleted_at);
CREATE INDEX IF NOT EXISTS idx_veh_make_model ON vehicles (make, model);
CREATE INDEX IF NOT EXISTS idx_veh_location ON vehicles (current_latitude, current_longitude);

-- ============================================================================
-- End of COMPANY 002 (postgres)
-- ============================================================================