ALTER TABLE tm_vehicles 
DROP COLUMN IF EXISTS vehicle_name,
DROP COLUMN IF EXISTS category,
DROP COLUMN IF EXISTS year,
DROP COLUMN IF EXISTS fuel_type,
DROP COLUMN IF EXISTS color,
DROP COLUMN IF EXISTS fuel_capacity,
DROP COLUMN IF EXISTS stnk_expiry,
DROP COLUMN IF EXISTS kir_expiry,
DROP COLUMN IF EXISTS notes,
DROP COLUMN IF EXISTS gps_install_date;
