ALTER TABLE th_route_assignments ALTER COLUMN end_date TYPE TIMESTAMP WITH TIME ZONE USING end_date::TIMESTAMP WITH TIME ZONE;
ALTER TABLE th_route_assignments RENAME COLUMN end_date TO end_time;
ALTER TABLE tm_driver_vehicles ALTER COLUMN unassigned_at TYPE TIMESTAMP WITH TIME ZONE USING unassigned_at::TIMESTAMP WITH TIME ZONE;
ALTER TABLE tm_driver_vehicles ALTER COLUMN assigned_at TYPE TIMESTAMP WITH TIME ZONE USING assigned_at::TIMESTAMP WITH TIME ZONE;
