-- ============================================================================
-- Migration: MASTER 007 — users (GLOBAL Auth Authority, PostgreSQL)
-- ============================================================================
-- 'SuperAdmin' sengaja masuk CHECK sejak awal (master 012 MySQL menambahkannya
-- lewat ALTER enum; di PG check constraint langsung memuat nilai tersebut).
-- ============================================================================

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    company_code VARCHAR(20) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(100) NOT NULL,

    username VARCHAR(191),
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    phone_number VARCHAR(20),
    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    phone_verified BOOLEAN NOT NULL DEFAULT FALSE,
    mfa_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    password_changed_at TIMESTAMP,
    failed_login_attempts INT NOT NULL DEFAULT 0,
    locked_until TIMESTAMP,
    locale VARCHAR(10) NOT NULL DEFAULT 'id',
    avatar_url VARCHAR(512),

    role TEXT NOT NULL
        CHECK (role IN ('SuperAdmin','Admin','Manager','Operator','Driver')),
    status TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active','inactive','suspended')),
    last_login TIMESTAMP,

    created_by BIGINT,
    updated_by BIGINT,
    deleted_at TIMESTAMP,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT fk_users_company FOREIGN KEY (company_id) REFERENCES companies(id)
);
CREATE INDEX IF NOT EXISTS idx_usr_company ON users (company_id);
CREATE INDEX IF NOT EXISTS idx_usr_company_code ON users (company_code);
CREATE INDEX IF NOT EXISTS idx_usr_email ON users (email);
CREATE INDEX IF NOT EXISTS idx_usr_username ON users (username);
CREATE INDEX IF NOT EXISTS idx_usr_role ON users (role);
CREATE INDEX IF NOT EXISTS idx_usr_locked ON users (locked_until);
CREATE INDEX IF NOT EXISTS idx_usr_locale ON users (locale);
CREATE INDEX IF NOT EXISTS idx_usr_deleted ON users (deleted_at);

-- ============================================================================
-- End of MASTER 007 (postgres)
-- ============================================================================