-- ============================================================================
-- Migration: MASTER 008 — tm_users (B2B auth authority, PRD §6.1)
-- ============================================================================
-- Multi-tenant (B2B) authentication authority. Roles are global; the effective
-- role inside a tenant is resolved through the company schema
-- (tm_user_company_access.role_override, B2).
--
-- Tenant admins are auto-created when a company is provisioned (FR-5.5):
-- password `Admin@123` (env PASSWORD_DEFAULT_TENANT_ADMIN) and
-- must_change_password = TRUE. Implementation lands in B2/B11; the columns are
-- created here so the schema never needs a breaking change later.

CREATE TABLE IF NOT EXISTS tm_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT,
    company_code VARCHAR(20),
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(100) NOT NULL,

    username VARCHAR(191),
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    phone_number VARCHAR(20),
    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    phone_verified BOOLEAN NOT NULL DEFAULT FALSE,
    mfa_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    must_change_password BOOLEAN NOT NULL DEFAULT FALSE,
    password_changed_at TIMESTAMPTZ,
    failed_login_attempts INT NOT NULL DEFAULT 0,
    locked_until TIMESTAMPTZ,
    locale VARCHAR(10) NOT NULL DEFAULT 'id',
    avatar_url VARCHAR(512),

    global_role TEXT NOT NULL CHECK (global_role IN ('SuperAdmin', 'Admin', 'Manager', 'Operator', 'Driver')),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    last_login_at TIMESTAMPTZ,

    created_by BIGINT,
    updated_by BIGINT,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    delete_reason VARCHAR(255),

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_tm_users_email UNIQUE (email),
    CONSTRAINT uq_tm_users_username UNIQUE (username),
    CONSTRAINT fk_tm_users_company FOREIGN KEY (company_id) REFERENCES tm_companies (id)
);
CREATE INDEX IF NOT EXISTS idx_tm_users_company ON tm_users (company_id);
CREATE INDEX IF NOT EXISTS idx_tm_users_company_code ON tm_users (company_code);
CREATE INDEX IF NOT EXISTS idx_tm_users_role ON tm_users (global_role);
CREATE INDEX IF NOT EXISTS idx_tm_users_active ON tm_users (is_active);
CREATE INDEX IF NOT EXISTS idx_tm_users_locked ON tm_users (locked_until);
CREATE INDEX IF NOT EXISTS idx_tm_users_deleted ON tm_users (deleted_at);