-- ============================================================================
-- Migration: MASTER 009 — tm_users_b2c (B2C auth authority, PRD §6.1)
-- ============================================================================
-- Consumer/single-tenant users. Fully isolated from the B2B tenant model:
-- no company_code, no cross access to any B2B tenant (roles USER|OWNER only).

CREATE TABLE IF NOT EXISTS tm_users_b2c (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    phone VARCHAR(20),

    role TEXT NOT NULL DEFAULT 'USER' CHECK (role IN ('USER', 'OWNER')),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    must_change_password BOOLEAN NOT NULL DEFAULT FALSE,
    password_changed_at TIMESTAMPTZ,
    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    failed_login_attempts INT NOT NULL DEFAULT 0,
    locked_until TIMESTAMPTZ,
    locale VARCHAR(10) NOT NULL DEFAULT 'id',
    last_login_at TIMESTAMPTZ,

    created_by BIGINT,
    updated_by BIGINT,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    delete_reason VARCHAR(255),

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_tm_users_b2c_email UNIQUE (email)
);
CREATE INDEX IF NOT EXISTS idx_tm_users_b2c_role ON tm_users_b2c (role);
CREATE INDEX IF NOT EXISTS idx_tm_users_b2c_deleted ON tm_users_b2c (deleted_at);