CREATE TABLE IF NOT EXISTS tm_gps_devices (
    imei VARCHAR(50) PRIMARY KEY,
    sim_number VARCHAR(50),
    protocol VARCHAR(50),
    assigned_company VARCHAR(255) REFERENCES tm_companies(code) ON DELETE SET NULL,
    status VARCHAR(50) DEFAULT 'idle',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
