-- ============================================================================
-- MASTER reference 001 — countries (ISO 3166-1, mledoze)
-- AUTO-GENERATED oleh backend/database/tools/genregions (jangan edit manual).
-- Sumber: https://raw.githubusercontent.com/mledoze/countries/master/countries.json
-- Idempotent: INSERT ... ON DUPLICATE KEY UPDATE.
-- ============================================================================


INSERT INTO countries (iso_code, iso_code_3, name, phone_code, currency_code, is_active) VALUES
  ('AD', 'AND', 'Andorra', '+376', 'EUR', TRUE),
  ('AE', 'ARE', 'United Arab Emirates', '+971', 'AED', TRUE),
  ('AF', 'AFG', 'Afghanistan', '+93', 'AFN', TRUE),
  ('AG', 'ATG', 'Antigua and Barbuda', '+1', 'XCD', TRUE),
  ('AI', 'AIA', 'Anguilla', '+1', 'XCD', TRUE),
  ('AL', 'ALB', 'Albania', '+355', 'ALL', TRUE),
  ('AM', 'ARM', 'Armenia', '+374', 'AMD', TRUE),
  ('AO', 'AGO', 'Angola', '+244', 'AOA', TRUE),
  ('AQ', 'ATA', 'Antarctica', '', '', TRUE),
  ('AR', 'ARG', 'Argentina', '+54', 'ARS', TRUE),
  ('AS', 'ASM', 'American Samoa', '+1', 'USD', TRUE),
  ('AT', 'AUT', 'Austria', '+43', 'EUR', TRUE),
  ('AU', 'AUS', 'Australia', '+61', 'AUD', TRUE),
  ('AW', 'ABW', 'Aruba', '+297', 'AWG', TRUE),
  ('AX', 'ALA', 'Åland Islands', '+3', 'EUR', TRUE),
  ('AZ', 'AZE', 'Azerbaijan', '+994', 'AZN', TRUE),
  ('BA', 'BIH', 'Bosnia and Herzegovina', '+387', 'BAM', TRUE),
  ('BB', 'BRB', 'Barbados', '+1', 'BBD', TRUE),
  ('BD', 'BGD', 'Bangladesh', '+880', 'BDT', TRUE),
  ('BE', 'BEL', 'Belgium', '+32', 'EUR', TRUE),
  ('BF', 'BFA', 'Burkina Faso', '+226', 'XOF', TRUE),
  ('BG', 'BGR', 'Bulgaria', '+359', 'EUR', TRUE),
  ('BH', 'BHR', 'Bahrain', '+973', 'BHD', TRUE),
  ('BI', 'BDI', 'Burundi', '+257', 'BIF', TRUE),
  ('BJ', 'BEN', 'Benin', '+229', 'XOF', TRUE),
  ('BL', 'BLM', 'Saint Barthélemy', '+590', 'EUR', TRUE),
  ('BM', 'BMU', 'Bermuda', '+1', 'BMD', TRUE),
  ('BN', 'BRN', 'Brunei', '+673', 'BND', TRUE),
  ('BO', 'BOL', 'Bolivia', '+591', 'BOB', TRUE),
  ('BQ', 'BES', 'Caribbean Netherlands', '+599', 'USD', TRUE),
  ('BR', 'BRA', 'Brazil', '+55', 'BRL', TRUE),
  ('BS', 'BHS', 'Bahamas', '+1', 'BSD', TRUE),
  ('BT', 'BTN', 'Bhutan', '+975', 'BTN', TRUE),
  ('BV', 'BVT', 'Bouvet Island', '+47', '', TRUE),
  ('BW', 'BWA', 'Botswana', '+267', 'BWP', TRUE),
  ('BY', 'BLR', 'Belarus', '+375', 'BYN', TRUE),
  ('BZ', 'BLZ', 'Belize', '+501', 'BZD', TRUE),
  ('CA', 'CAN', 'Canada', '+1', 'CAD', TRUE),
  ('CC', 'CCK', 'Cocos (Keeling) Islands', '+61', 'AUD', TRUE),
  ('CD', 'COD', 'DR Congo', '+243', 'CDF', TRUE),
  ('CF', 'CAF', 'Central African Republic', '+236', 'XAF', TRUE),
  ('CG', 'COG', 'Congo', '+242', 'XAF', TRUE),
  ('CH', 'CHE', 'Switzerland', '+41', 'CHF', TRUE),
  ('CI', 'CIV', 'Ivory Coast', '+225', 'XOF', TRUE),
  ('CK', 'COK', 'Cook Islands', '+682', 'CKD', TRUE),
  ('CL', 'CHL', 'Chile', '+56', 'CLP', TRUE),
  ('CM', 'CMR', 'Cameroon', '+237', 'XAF', TRUE),
  ('CN', 'CHN', 'China', '+86', 'CNY', TRUE),
  ('CO', 'COL', 'Colombia', '+57', 'COP', TRUE),
  ('CR', 'CRI', 'Costa Rica', '+506', 'CRC', TRUE),
  ('CU', 'CUB', 'Cuba', '+53', 'CUC', TRUE),
  ('CV', 'CPV', 'Cape Verde', '+238', 'CVE', TRUE),
  ('CW', 'CUW', 'Curaçao', '+599', 'ANG', TRUE),
  ('CX', 'CXR', 'Christmas Island', '+61', 'AUD', TRUE),
  ('CY', 'CYP', 'Cyprus', '+357', 'EUR', TRUE),
  ('CZ', 'CZE', 'Czechia', '+420', 'CZK', TRUE),
  ('DE', 'DEU', 'Germany', '+49', 'EUR', TRUE),
  ('DJ', 'DJI', 'Djibouti', '+253', 'DJF', TRUE),
  ('DK', 'DNK', 'Denmark', '+45', 'DKK', TRUE),
  ('DM', 'DMA', 'Dominica', '+1', 'XCD', TRUE),
  ('DO', 'DOM', 'Dominican Republic', '+1', 'DOP', TRUE),
  ('DZ', 'DZA', 'Algeria', '+213', 'DZD', TRUE),
  ('EC', 'ECU', 'Ecuador', '+593', 'USD', TRUE),
  ('EE', 'EST', 'Estonia', '+372', 'EUR', TRUE),
  ('EG', 'EGY', 'Egypt', '+20', 'EGP', TRUE),
  ('EH', 'ESH', 'Western Sahara', '+2', 'DZD', TRUE),
  ('ER', 'ERI', 'Eritrea', '+291', 'ERN', TRUE),
  ('ES', 'ESP', 'Spain', '+34', 'EUR', TRUE),
  ('ET', 'ETH', 'Ethiopia', '+251', 'ETB', TRUE),
  ('FI', 'FIN', 'Finland', '+358', 'EUR', TRUE),
  ('FJ', 'FJI', 'Fiji', '+679', 'FJD', TRUE),
  ('FK', 'FLK', 'Falkland Islands', '+500', 'FKP', TRUE),
  ('FM', 'FSM', 'Micronesia', '+691', '', TRUE),
  ('FO', 'FRO', 'Faroe Islands', '+298', 'DKK', TRUE),
  ('FR', 'FRA', 'France', '+33', 'EUR', TRUE),
  ('GA', 'GAB', 'Gabon', '+241', 'XAF', TRUE),
  ('GB', 'GBR', 'United Kingdom', '+44', 'GBP', TRUE),
  ('GD', 'GRD', 'Grenada', '+1', 'XCD', TRUE),
  ('GE', 'GEO', 'Georgia', '+995', 'GEL', TRUE),
  ('GF', 'GUF', 'French Guiana', '+594', 'EUR', TRUE),
  ('GG', 'GGY', 'Guernsey', '+44', 'GBP', TRUE),
  ('GH', 'GHA', 'Ghana', '+233', 'GHS', TRUE),
  ('GI', 'GIB', 'Gibraltar', '+350', 'GIP', TRUE),
  ('GL', 'GRL', 'Greenland', '+299', 'DKK', TRUE),
  ('GM', 'GMB', 'Gambia', '+220', 'GMD', TRUE),
  ('GN', 'GIN', 'Guinea', '+224', 'GNF', TRUE),
  ('GP', 'GLP', 'Guadeloupe', '+590', 'EUR', TRUE),
  ('GQ', 'GNQ', 'Equatorial Guinea', '+240', 'XAF', TRUE),
  ('GR', 'GRC', 'Greece', '+30', 'EUR', TRUE),
  ('GS', 'SGS', 'South Georgia', '+500', 'SHP', TRUE),
  ('GT', 'GTM', 'Guatemala', '+502', 'GTQ', TRUE),
  ('GU', 'GUM', 'Guam', '+1', 'USD', TRUE),
  ('GW', 'GNB', 'Guinea-Bissau', '+245', 'XOF', TRUE),
  ('GY', 'GUY', 'Guyana', '+592', 'GYD', TRUE),
  ('HK', 'HKG', 'Hong Kong', '+852', 'HKD', TRUE),
  ('HM', 'HMD', 'Heard Island and McDonald Islands', '', '', TRUE),
  ('HN', 'HND', 'Honduras', '+504', 'HNL', TRUE),
  ('HR', 'HRV', 'Croatia', '+385', 'EUR', TRUE),
  ('HT', 'HTI', 'Haiti', '+509', 'HTG', TRUE),
  ('HU', 'HUN', 'Hungary', '+36', 'HUF', TRUE),
  ('ID', 'IDN', 'Indonesia', '+62', 'IDR', TRUE),
  ('IE', 'IRL', 'Ireland', '+353', 'EUR', TRUE),
  ('IL', 'ISR', 'Israel', '+972', 'ILS', TRUE),
  ('IM', 'IMN', 'Isle of Man', '+44', 'GBP', TRUE),
  ('IN', 'IND', 'India', '+91', 'INR', TRUE),
  ('IO', 'IOT', 'British Indian Ocean Territory', '+246', 'USD', TRUE),
  ('IQ', 'IRQ', 'Iraq', '+964', 'IQD', TRUE),
  ('IR', 'IRN', 'Iran', '+98', 'IRR', TRUE),
  ('IS', 'ISL', 'Iceland', '+354', 'ISK', TRUE),
  ('IT', 'ITA', 'Italy', '+39', 'EUR', TRUE),
  ('JE', 'JEY', 'Jersey', '+44', 'GBP', TRUE),
  ('JM', 'JAM', 'Jamaica', '+1', 'JMD', TRUE),
  ('JO', 'JOR', 'Jordan', '+962', 'JOD', TRUE),
  ('JP', 'JPN', 'Japan', '+81', 'JPY', TRUE),
  ('KE', 'KEN', 'Kenya', '+254', 'KES', TRUE),
  ('KG', 'KGZ', 'Kyrgyzstan', '+996', 'KGS', TRUE),
  ('KH', 'KHM', 'Cambodia', '+855', 'KHR', TRUE),
  ('KI', 'KIR', 'Kiribati', '+686', 'AUD', TRUE),
  ('KM', 'COM', 'Comoros', '+269', 'KMF', TRUE),
  ('KN', 'KNA', 'Saint Kitts and Nevis', '+1', 'XCD', TRUE),
  ('KP', 'PRK', 'North Korea', '+850', 'KPW', TRUE),
  ('KR', 'KOR', 'South Korea', '+82', 'KRW', TRUE),
  ('KW', 'KWT', 'Kuwait', '+965', 'KWD', TRUE),
  ('KY', 'CYM', 'Cayman Islands', '+1', 'KYD', TRUE),
  ('KZ', 'KAZ', 'Kazakhstan', '+76', 'KZT', TRUE),
  ('LA', 'LAO', 'Laos', '+856', 'LAK', TRUE),
  ('LB', 'LBN', 'Lebanon', '+961', 'LBP', TRUE),
  ('LC', 'LCA', 'Saint Lucia', '+1', 'XCD', TRUE),
  ('LI', 'LIE', 'Liechtenstein', '+423', 'CHF', TRUE),
  ('LK', 'LKA', 'Sri Lanka', '+94', 'LKR', TRUE),
  ('LR', 'LBR', 'Liberia', '+231', 'LRD', TRUE),
  ('LS', 'LSO', 'Lesotho', '+266', 'LSL', TRUE),
  ('LT', 'LTU', 'Lithuania', '+370', 'EUR', TRUE),
  ('LU', 'LUX', 'Luxembourg', '+352', 'EUR', TRUE),
  ('LV', 'LVA', 'Latvia', '+371', 'EUR', TRUE),
  ('LY', 'LBY', 'Libya', '+218', 'LYD', TRUE),
  ('MA', 'MAR', 'Morocco', '+212', 'MAD', TRUE),
  ('MC', 'MCO', 'Monaco', '+377', 'EUR', TRUE),
  ('MD', 'MDA', 'Moldova', '+373', 'MDL', TRUE),
  ('ME', 'MNE', 'Montenegro', '+382', 'EUR', TRUE),
  ('MF', 'MAF', 'Saint Martin', '+590', 'EUR', TRUE),
  ('MG', 'MDG', 'Madagascar', '+261', 'MGA', TRUE),
  ('MH', 'MHL', 'Marshall Islands', '+692', 'USD', TRUE),
  ('MK', 'MKD', 'North Macedonia', '+389', 'MKD', TRUE),
  ('ML', 'MLI', 'Mali', '+223', 'XOF', TRUE),
  ('MM', 'MMR', 'Myanmar', '+95', 'MMK', TRUE),
  ('MN', 'MNG', 'Mongolia', '+976', 'MNT', TRUE),
  ('MO', 'MAC', 'Macau', '+853', 'MOP', TRUE),
  ('MP', 'MNP', 'Northern Mariana Islands', '+1', 'USD', TRUE),
  ('MQ', 'MTQ', 'Martinique', '+596', 'EUR', TRUE),
  ('MR', 'MRT', 'Mauritania', '+222', 'MRU', TRUE),
  ('MS', 'MSR', 'Montserrat', '+1', 'XCD', TRUE),
  ('MT', 'MLT', 'Malta', '+356', 'EUR', TRUE),
  ('MU', 'MUS', 'Mauritius', '+230', 'MUR', TRUE),
  ('MV', 'MDV', 'Maldives', '+960', 'MVR', TRUE),
  ('MW', 'MWI', 'Malawi', '+265', 'MWK', TRUE),
  ('MX', 'MEX', 'Mexico', '+52', 'MXN', TRUE),
  ('MY', 'MYS', 'Malaysia', '+60', 'MYR', TRUE),
  ('MZ', 'MOZ', 'Mozambique', '+258', 'MZN', TRUE),
  ('NA', 'NAM', 'Namibia', '+264', 'NAD', TRUE),
  ('NC', 'NCL', 'New Caledonia', '+687', 'XPF', TRUE),
  ('NE', 'NER', 'Niger', '+227', 'XOF', TRUE),
  ('NF', 'NFK', 'Norfolk Island', '+672', 'AUD', TRUE),
  ('NG', 'NGA', 'Nigeria', '+234', 'NGN', TRUE),
  ('NI', 'NIC', 'Nicaragua', '+505', 'NIO', TRUE),
  ('NL', 'NLD', 'Netherlands', '+31', 'EUR', TRUE),
  ('NO', 'NOR', 'Norway', '+47', 'NOK', TRUE),
  ('NP', 'NPL', 'Nepal', '+977', 'NPR', TRUE),
  ('NR', 'NRU', 'Nauru', '+674', 'AUD', TRUE),
  ('NU', 'NIU', 'Niue', '+683', 'NZD', TRUE),
  ('NZ', 'NZL', 'New Zealand', '+64', 'NZD', TRUE),
  ('OM', 'OMN', 'Oman', '+968', 'OMR', TRUE),
  ('PA', 'PAN', 'Panama', '+507', 'PAB', TRUE),
  ('PE', 'PER', 'Peru', '+51', 'PEN', TRUE),
  ('PF', 'PYF', 'French Polynesia', '+689', 'XPF', TRUE),
  ('PG', 'PNG', 'Papua New Guinea', '+675', 'PGK', TRUE),
  ('PH', 'PHL', 'Philippines', '+63', 'PHP', TRUE),
  ('PK', 'PAK', 'Pakistan', '+92', 'PKR', TRUE),
  ('PL', 'POL', 'Poland', '+48', 'PLN', TRUE),
  ('PM', 'SPM', 'Saint Pierre and Miquelon', '+508', 'EUR', TRUE),
  ('PN', 'PCN', 'Pitcairn Islands', '+64', 'NZD', TRUE),
  ('PR', 'PRI', 'Puerto Rico', '+1', 'USD', TRUE),
  ('PS', 'PSE', 'Palestine', '+970', 'EGP', TRUE),
  ('PT', 'PRT', 'Portugal', '+351', 'EUR', TRUE),
  ('PW', 'PLW', 'Palau', '+680', 'USD', TRUE),
  ('PY', 'PRY', 'Paraguay', '+595', 'PYG', TRUE),
  ('QA', 'QAT', 'Qatar', '+974', 'QAR', TRUE),
  ('RE', 'REU', 'Réunion', '+262', 'EUR', TRUE),
  ('RO', 'ROU', 'Romania', '+40', 'RON', TRUE),
  ('RS', 'SRB', 'Serbia', '+381', 'RSD', TRUE),
  ('RU', 'RUS', 'Russia', '+73', 'RUB', TRUE),
  ('RW', 'RWA', 'Rwanda', '+250', 'RWF', TRUE),
  ('SA', 'SAU', 'Saudi Arabia', '+966', 'SAR', TRUE),
  ('SB', 'SLB', 'Solomon Islands', '+677', 'SBD', TRUE),
  ('SC', 'SYC', 'Seychelles', '+248', 'SCR', TRUE),
  ('SD', 'SDN', 'Sudan', '+249', 'SDG', TRUE),
  ('SE', 'SWE', 'Sweden', '+46', 'SEK', TRUE),
  ('SG', 'SGP', 'Singapore', '+65', 'SGD', TRUE),
  ('SH', 'SHN', 'Saint Helena, Ascension and Tristan da Cunha', '+290', 'GBP', TRUE),
  ('SI', 'SVN', 'Slovenia', '+386', 'EUR', TRUE),
  ('SJ', 'SJM', 'Svalbard and Jan Mayen', '+4', 'NOK', TRUE),
  ('SK', 'SVK', 'Slovakia', '+421', 'EUR', TRUE),
  ('SL', 'SLE', 'Sierra Leone', '+232', 'SLE', TRUE),
  ('SM', 'SMR', 'San Marino', '+378', 'EUR', TRUE),
  ('SN', 'SEN', 'Senegal', '+221', 'XOF', TRUE),
  ('SO', 'SOM', 'Somalia', '+252', 'SOS', TRUE),
  ('SR', 'SUR', 'Suriname', '+597', 'SRD', TRUE),
  ('SS', 'SSD', 'South Sudan', '+211', 'SSP', TRUE),
  ('ST', 'STP', 'São Tomé and Príncipe', '+239', 'STN', TRUE),
  ('SV', 'SLV', 'El Salvador', '+503', 'USD', TRUE),
  ('SX', 'SXM', 'Sint Maarten', '+1', 'ANG', TRUE),
  ('SY', 'SYR', 'Syria', '+963', 'SYP', TRUE),
  ('SZ', 'SWZ', 'Eswatini', '+268', 'SZL', TRUE),
  ('TC', 'TCA', 'Turks and Caicos Islands', '+1', 'USD', TRUE),
  ('TD', 'TCD', 'Chad', '+235', 'XAF', TRUE),
  ('TF', 'ATF', 'French Southern and Antarctic Lands', '+262', 'EUR', TRUE),
  ('TG', 'TGO', 'Togo', '+228', 'XOF', TRUE),
  ('TH', 'THA', 'Thailand', '+66', 'THB', TRUE),
  ('TJ', 'TJK', 'Tajikistan', '+992', 'TJS', TRUE),
  ('TK', 'TKL', 'Tokelau', '+690', 'NZD', TRUE),
  ('TL', 'TLS', 'Timor-Leste', '+670', 'USD', TRUE),
  ('TM', 'TKM', 'Turkmenistan', '+993', 'TMT', TRUE),
  ('TN', 'TUN', 'Tunisia', '+216', 'TND', TRUE),
  ('TO', 'TON', 'Tonga', '+676', 'TOP', TRUE),
  ('TR', 'TUR', 'Türkiye', '+90', 'TRY', TRUE),
  ('TT', 'TTO', 'Trinidad and Tobago', '+1', 'TTD', TRUE),
  ('TV', 'TUV', 'Tuvalu', '+688', 'AUD', TRUE),
  ('TW', 'TWN', 'Taiwan', '+886', 'TWD', TRUE),
  ('TZ', 'TZA', 'Tanzania', '+255', 'TZS', TRUE),
  ('UA', 'UKR', 'Ukraine', '+380', 'UAH', TRUE),
  ('UG', 'UGA', 'Uganda', '+256', 'UGX', TRUE),
  ('UM', 'UMI', 'United States Minor Outlying Islands', '+268', 'USD', TRUE),
  ('US', 'USA', 'United States', '+1', 'USD', TRUE),
  ('UY', 'URY', 'Uruguay', '+598', 'UYU', TRUE),
  ('UZ', 'UZB', 'Uzbekistan', '+998', 'UZS', TRUE),
  ('VA', 'VAT', 'Vatican City', '+3', 'EUR', TRUE),
  ('VC', 'VCT', 'Saint Vincent and the Grenadines', '+1', 'XCD', TRUE),
  ('VE', 'VEN', 'Venezuela', '+58', 'VES', TRUE),
  ('VG', 'VGB', 'British Virgin Islands', '+1', 'USD', TRUE),
  ('VI', 'VIR', 'United States Virgin Islands', '+1', 'USD', TRUE),
  ('VN', 'VNM', 'Vietnam', '+84', 'VND', TRUE),
  ('VU', 'VUT', 'Vanuatu', '+678', 'VUV', TRUE),
  ('WF', 'WLF', 'Wallis and Futuna', '+681', 'XPF', TRUE),
  ('WS', 'WSM', 'Samoa', '+685', 'WST', TRUE),
  ('XK', 'UNK', 'Kosovo', '+383', 'EUR', FALSE),
  ('YE', 'YEM', 'Yemen', '+967', 'YER', TRUE),
  ('YT', 'MYT', 'Mayotte', '+262', 'EUR', TRUE),
  ('ZA', 'ZAF', 'South Africa', '+27', 'ZAR', TRUE),
  ('ZM', 'ZMB', 'Zambia', '+260', 'ZMW', TRUE),
  ('ZW', 'ZWE', 'Zimbabwe', '+263', 'BWP', TRUE)
ON DUPLICATE KEY UPDATE name=VALUES(name), phone_code=VALUES(phone_code), currency_code=VALUES(currency_code), is_active=VALUES(is_active);
