-- ============================================================================
-- MASTER reference 003 — cities / kabupaten-kota (BPS)
-- AUTO-GENERATED oleh backend/database/tools/genregions (jangan edit manual).
-- Sumber: fityannugroho/idn-area-data regencies.csv + geonames ADM2 coords
-- Idempotent: INSERT ... ON DUPLICATE KEY UPDATE.
-- ============================================================================


INSERT INTO cities (country_id, province_id, code, name, latitude, longitude) VALUES
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '11'), '11.01', 'Kabupaten Aceh Selatan', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '11'), '11.02', 'Kabupaten Aceh Tenggara', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '11'), '11.03', 'Kabupaten Aceh Timur', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '11'), '11.04', 'Kabupaten Aceh Tengah', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '11'), '11.05', 'Kabupaten Aceh Barat', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '11'), '11.06', 'Kabupaten Aceh Besar', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '11'), '11.07', 'Kabupaten Pidie', 5.080000, 96.110000),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '11'), '11.08', 'Kabupaten Aceh Utara', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '11'), '11.09', 'Kabupaten Simeulue', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '11'), '11.10', 'Kabupaten Aceh Singkil', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '11'), '11.11', 'Kabupaten Bireuen', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '11'), '11.12', 'Kabupaten Aceh Barat Daya', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '11'), '11.13', 'Kabupaten Gayo Lues', 3.950000, 97.390000),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '11'), '11.14', 'Kabupaten Aceh Jaya', 4.860000, 95.640000),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '11'), '11.15', 'Kabupaten Nagan Raya', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '11'), '11.16', 'Kabupaten Aceh Tamiang', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '11'), '11.17', 'Kabupaten Bener Meriah', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '11'), '11.18', 'Kabupaten Pidie Jaya', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '11'), '11.71', 'Kota Banda Aceh', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '11'), '11.72', 'Kota Sabang', 5.879440, 95.332230),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '11'), '11.73', 'Kota Lhokseumawe', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '11'), '11.74', 'Kota Langsa', 4.470000, 97.930000),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '11'), '11.75', 'Kota Subulussalam', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '12'), '12.01', 'Kabupaten Tapanuli Tengah', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '12'), '12.02', 'Kabupaten Tapanuli Utara', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '12'), '12.03', 'Kabupaten Tapanuli Selatan', 1.516670, 99.250000),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '12'), '12.04', 'Kabupaten Nias', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '12'), '12.05', 'Kabupaten Langkat', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '12'), '12.06', 'Kabupaten Karo', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '12'), '12.07', 'Kabupaten Deli Serdang', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '12'), '12.08', 'Kabupaten Simalungun', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '12'), '12.09', 'Kabupaten Asahan', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '12'), '12.10', 'Kabupaten Labuhanbatu', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '12'), '12.11', 'Kabupaten Dairi', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '12'), '12.12', 'Kabupaten Toba', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '12'), '12.13', 'Kabupaten Mandailing Natal', 0.783780, 99.254950),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '12'), '12.14', 'Kabupaten Nias Selatan', 0.770000, 97.750000),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '12'), '12.15', 'Kabupaten Pakpak Bharat', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '12'), '12.16', 'Kabupaten Humbang Hasundutan', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '12'), '12.17', 'Kabupaten Samosir', 2.640250, 98.715250),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '12'), '12.18', 'Kabupaten Serdang Bedagai', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '12'), '12.19', 'Kabupaten Batu Bara', 3.161660, 99.526520),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '12'), '12.20', 'Kabupaten Padang Lawas Utara', 1.460110, 99.673460),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '12'), '12.21', 'Kabupaten Padang Lawas', 1.156590, 99.811360),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '12'), '12.22', 'Kabupaten Labuhanbatu Selatan', 1.983000, 100.097600),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '12'), '12.23', 'Kabupaten Labuhanbatu Utara', 2.333490, 99.637760),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '12'), '12.24', 'Kabupaten Nias Utara', 1.330370, 97.319640),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '12'), '12.25', 'Kabupaten Nias Barat', 1.059660, 97.586060),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '12'), '12.71', 'Kota Medan', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '12'), '12.72', 'Kota Pematangsiantar', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '12'), '12.73', 'Kota Sibolga', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '12'), '12.74', 'Kota Tanjungbalai', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '12'), '12.75', 'Kota Binjai', 3.598600, 98.480280),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '12'), '12.76', 'Kota Tebing Tinggi', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '12'), '12.77', 'Kota Padangsidimpuan', 1.373750, 99.268430),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '12'), '12.78', 'Kota Gunungsitoli', 1.327310, 97.550180),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '13'), '13.01', 'Kabupaten Pesisir Selatan', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '13'), '13.02', 'Kabupaten Solok', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '13'), '13.03', 'Kabupaten Sijunjung', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '13'), '13.04', 'Kabupaten Tanah Datar', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '13'), '13.05', 'Kabupaten Padang Pariaman', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '13'), '13.06', 'Kabupaten Agam', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '13'), '13.07', 'Kabupaten Lima Puluh Kota', -0.016800, 100.587200),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '13'), '13.08', 'Kabupaten Pasaman', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '13'), '13.09', 'Kabupaten Kepulauan Mentawai', -1.359270, 98.895520),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '13'), '13.10', 'Kabupaten Dharmasraya', -1.250600, 101.586450),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '13'), '13.11', 'Kabupaten Solok Selatan', -1.233330, 101.417000),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '13'), '13.12', 'Kabupaten Pasaman Barat', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '13'), '13.71', 'Kota Padang', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '13'), '13.72', 'Kota Solok', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '13'), '13.73', 'Kota Sawahlunto', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '13'), '13.74', 'Kota Padang Panjang', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '13'), '13.75', 'Kota Bukittinggi', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '13'), '13.76', 'Kota Payakumbuh', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '13'), '13.77', 'Kota Pariaman', -0.626820, 100.120470),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '14'), '14.01', 'Kabupaten Kampar', 0.234400, 101.213100),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '14'), '14.02', 'Kabupaten Indragiri Hulu', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '14'), '14.03', 'Kabupaten Bengkalis', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '14'), '14.04', 'Kabupaten Indragiri Hilir', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '14'), '14.05', 'Kabupaten Pelalawan', 0.208220, 102.186070),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '14'), '14.06', 'Kabupaten Rokan Hulu', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '14'), '14.07', 'Kabupaten Rokan Hilir', 2.165990, 100.825140),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '14'), '14.08', 'Kabupaten Siak', 0.974530, 102.013550),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '14'), '14.09', 'Kabupaten Kuantan Singingi', -0.475320, 101.458570),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '14'), '14.10', 'Kabupaten Kepulauan Meranti', 0.974880, 102.695390),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '14'), '14.71', 'Kota Pekanbaru', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '14'), '14.72', 'Kota Dumai', 1.615920, 101.491700),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '15'), '15.01', 'Kabupaten Kerinci', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '15'), '15.02', 'Kabupaten Merangin', -2.069330, 102.133030),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '15'), '15.03', 'Kabupaten Sarolangun', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '15'), '15.04', 'Kabupaten Batanghari', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '15'), '15.05', 'Kabupaten Muaro Jambi', -1.552140, 103.821630),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '15'), '15.06', 'Kabupaten Tanjung Jabung Barat', -1.154400, 103.244020),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '15'), '15.07', 'Kabupaten Tanjung Jabung Timur', -1.131980, 103.617550),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '15'), '15.08', 'Kabupaten Bungo', -1.502220, 101.960000),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '15'), '15.09', 'Kabupaten Tebo', -1.455760, 102.374730),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '15'), '15.71', 'Kota Jambi', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '15'), '15.72', 'Kota Sungai Penuh', -2.108960, 101.321750),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '16'), '16.01', 'Kabupaten Ogan Komering Ulu', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '16'), '16.02', 'Kabupaten Ogan Komering Ilir', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '16'), '16.03', 'Kabupaten Muara Enim', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '16'), '16.04', 'Kabupaten Lahat', -3.786400, 103.542800),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '16'), '16.05', 'Kabupaten Musi Rawas', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '16'), '16.06', 'Kabupaten Musi Banyuasin', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '16'), '16.07', 'Kabupaten Banyuasin', -2.883330, 104.383060),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '16'), '16.08', 'Kabupaten Ogan Komering Ulu Timur', -3.856790, 104.752090),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '16'), '16.09', 'Kabupaten Ogan Komering Ulu Selatan', -4.657280, 104.006590),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '16'), '16.10', 'Kabupaten Ogan Ilir', -3.431860, 104.627270),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '16'), '16.11', 'Kabupaten Empat Lawang', -3.716290, 102.945110),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '16'), '16.12', 'Kabupaten Penukal Abab Lematang Ilir', -3.213420, 104.087220),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '16'), '16.13', 'Kabupaten Musi Rawas Utara', -2.706060, 102.763200),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '16'), '16.71', 'Kota Palembang', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '16'), '16.72', 'Kota Pagar Alam', -4.130550, 103.268220),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '16'), '16.73', 'Kota Lubuk Linggau', -3.293080, 102.855030),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '16'), '16.74', 'Kota Prabumulih', -3.462020, 104.222900),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '17'), '17.01', 'Kabupaten Bengkulu Selatan', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '17'), '17.02', 'Kabupaten Rejang Lebong', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '17'), '17.03', 'Kabupaten Bengkulu Utara', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '17'), '17.04', 'Kabupaten Kaur', -4.781790, 103.361090),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '17'), '17.05', 'Kabupaten Seluma', -3.966440, 102.474290),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '17'), '17.06', 'Kabupaten Mukomuko', -3.074380, 101.547660),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '17'), '17.07', 'Kabupaten Lebong', -3.242780, 102.334900),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '17'), '17.08', 'Kabupaten Kepahiang', -3.601940, 102.564240),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '17'), '17.09', 'Kabupaten Bengkulu Tengah', -3.677750, 102.396480),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '17'), '17.71', 'Kota Bengkulu', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '18'), '18.01', 'Kabupaten Lampung Selatan', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '18'), '18.02', 'Kabupaten Lampung Tengah', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '18'), '18.03', 'Kabupaten Lampung Utara', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '18'), '18.04', 'Kabupaten Lampung Barat', -5.149040, 104.193090),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '18'), '18.05', 'Kabupaten Tulang Bawang', -4.206040, 105.579990),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '18'), '18.06', 'Kabupaten Tanggamus', -5.385080, 104.623490),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '18'), '18.07', 'Kabupaten Lampung Timur', -5.102730, 105.680030),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '18'), '18.08', 'Kabupaten Way Kanan', -4.447050, 104.527530),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '18'), '18.09', 'Kabupaten Pesawaran', -5.429800, 105.178990),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '18'), '18.10', 'Kabupaten Pringsewu', -5.422110, 104.934540),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '18'), '18.11', 'Kabupaten Mesuji', -4.043900, 105.401300),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '18'), '18.12', 'Kabupaten Tulang Bawang Barat', -4.433560, 105.160040),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '18'), '18.13', 'Kabupaten Pesisir Barat', -5.193230, 103.939760),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '18'), '18.71', 'Kota Bandar Lampung', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '18'), '18.72', 'Kota Metro', -5.118560, 105.299490),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '19'), '19.01', 'Kabupaten Bangka', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '19'), '19.02', 'Kabupaten Belitung', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '19'), '19.03', 'Kabupaten Bangka Selatan', -2.668030, 106.012570),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '19'), '19.04', 'Kabupaten Bangka Tengah', -2.339890, 106.114200),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '19'), '19.05', 'Kabupaten Bangka Barat', -1.958390, 105.537410),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '19'), '19.06', 'Kabupaten Belitung Timur', -2.962700, 108.152160),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '19'), '19.71', 'Kota Pangkal Pinang', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '21'), '21.01', 'Kabupaten Bintan', 0.950000, 104.619440),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '21'), '21.02', 'Kabupaten Karimun', 0.807640, 103.419110),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '21'), '21.03', 'Kabupaten Natuna', 4.714170, 107.976390),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '21'), '21.04', 'Kabupaten Lingga', -0.509100, 104.414480),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '21'), '21.05', 'Kabupaten Kepulauan Anambas', 2.939660, 105.760710),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '21'), '21.71', 'Kota Batam', 1.052110, 104.028510),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '21'), '21.72', 'Kota Tanjung Pinang', 0.916830, 104.443290),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '31'), '31.01', 'Kabupaten Administrasi Kepulauan Seribu', -5.803080, 106.522570),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '31'), '31.71', 'Kota Administrasi Jakarta Pusat', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '31'), '31.72', 'Kota Administrasi Jakarta Utara', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '31'), '31.73', 'Kota Administrasi Jakarta Barat', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '31'), '31.74', 'Kota Administrasi Jakarta Selatan', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '31'), '31.75', 'Kota Administrasi Jakarta Timur', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '32'), '32.01', 'Kabupaten Bogor', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '32'), '32.02', 'Kabupaten Sukabumi', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '32'), '32.03', 'Kabupaten Cianjur', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '32'), '32.04', 'Kabupaten Bandung', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '32'), '32.05', 'Kabupaten Garut', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '32'), '32.06', 'Kabupaten Tasikmalaya', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '32'), '32.07', 'Kabupaten Ciamis', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '32'), '32.08', 'Kabupaten Kuningan', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '32'), '32.09', 'Kabupaten Cirebon', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '32'), '32.10', 'Kabupaten Majalengka', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '32'), '32.11', 'Kabupaten Sumedang', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '32'), '32.12', 'Kabupaten Indramayu', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '32'), '32.13', 'Kabupaten Subang', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '32'), '32.14', 'Kabupaten Purwakarta', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '32'), '32.15', 'Kabupaten Karawang', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '32'), '32.16', 'Kabupaten Bekasi', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '32'), '32.17', 'Kabupaten Bandung Barat', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '32'), '32.18', 'Kabupaten Pangandaran', -7.667300, 108.640370),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '32'), '32.71', 'Kota Bogor', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '32'), '32.72', 'Kota Sukabumi', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '32'), '32.73', 'Kota Bandung', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '32'), '32.74', 'Kota Cirebon', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '32'), '32.75', 'Kota Bekasi', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '32'), '32.76', 'Kota Depok', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '32'), '32.77', 'Kota Cimahi', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '32'), '32.78', 'Kota Tasikmalaya', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '32'), '32.79', 'Kota Banjar', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '33'), '33.01', 'Kabupaten Cilacap', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '33'), '33.02', 'Kabupaten Banyumas', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '33'), '33.03', 'Kabupaten Purbalingga', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '33'), '33.04', 'Kabupaten Banjarnegara', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '33'), '33.05', 'Kabupaten Kebumen', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '33'), '33.06', 'Kabupaten Purworejo', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '33'), '33.07', 'Kabupaten Wonosobo', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '33'), '33.08', 'Kabupaten Magelang', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '33'), '33.09', 'Kabupaten Boyolali', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '33'), '33.10', 'Kabupaten Klaten', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '33'), '33.11', 'Kabupaten Sukoharjo', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '33'), '33.12', 'Kabupaten Wonogiri', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '33'), '33.13', 'Kabupaten Karanganyar', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '33'), '33.14', 'Kabupaten Sragen', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '33'), '33.15', 'Kabupaten Grobogan', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '33'), '33.16', 'Kabupaten Blora', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '33'), '33.17', 'Kabupaten Rembang', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '33'), '33.18', 'Kabupaten Pati', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '33'), '33.19', 'Kabupaten Kudus', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '33'), '33.20', 'Kabupaten Jepara', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '33'), '33.21', 'Kabupaten Demak', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '33'), '33.22', 'Kabupaten Semarang', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '33'), '33.23', 'Kabupaten Temanggung', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '33'), '33.24', 'Kabupaten Kendal', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '33'), '33.25', 'Kabupaten Batang', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '33'), '33.26', 'Kabupaten Pekalongan', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '33'), '33.27', 'Kabupaten Pemalang', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '33'), '33.28', 'Kabupaten Tegal', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '33'), '33.29', 'Kabupaten Brebes', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '33'), '33.71', 'Kota Magelang', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '33'), '33.72', 'Kota Surakarta', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '33'), '33.73', 'Kota Salatiga', -7.332780, 110.483330),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '33'), '33.74', 'Kota Semarang', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '33'), '33.75', 'Kota Pekalongan', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '33'), '33.76', 'Kota Tegal', -6.868600, 109.112900),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '34'), '34.01', 'Kabupaten Kulon Progo', -7.812560, 110.151330),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '34'), '34.02', 'Kabupaten Bantul', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '34'), '34.03', 'Kabupaten Gunungkidul', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '34'), '34.04', 'Kabupaten Sleman', -7.681670, 110.323330),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '34'), '34.71', 'Kota Yogyakarta', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '35'), '35.01', 'Kabupaten Pacitan', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '35'), '35.02', 'Kabupaten Ponorogo', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '35'), '35.03', 'Kabupaten Trenggalek', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '35'), '35.04', 'Kabupaten Tulungagung', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '35'), '35.05', 'Kabupaten Blitar', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '35'), '35.06', 'Kabupaten Kediri', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '35'), '35.07', 'Kabupaten Malang', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '35'), '35.08', 'Kabupaten Lumajang', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '35'), '35.09', 'Kabupaten Jember', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '35'), '35.10', 'Kabupaten Banyuwangi', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '35'), '35.11', 'Kabupaten Bondowoso', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '35'), '35.12', 'Kabupaten Situbondo', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '35'), '35.13', 'Kabupaten Probolinggo', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '35'), '35.14', 'Kabupaten Pasuruan', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '35'), '35.15', 'Kabupaten Sidoarjo', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '35'), '35.16', 'Kabupaten Mojokerto', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '35'), '35.17', 'Kabupaten Jombang', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '35'), '35.18', 'Kabupaten Nganjuk', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '35'), '35.19', 'Kabupaten Madiun', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '35'), '35.20', 'Kabupaten Magetan', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '35'), '35.21', 'Kabupaten Ngawi', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '35'), '35.22', 'Kabupaten Bojonegoro', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '35'), '35.23', 'Kabupaten Tuban', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '35'), '35.24', 'Kabupaten Lamongan', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '35'), '35.25', 'Kabupaten Gresik', -7.193300, 112.553000),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '35'), '35.26', 'Kabupaten Bangkalan', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '35'), '35.27', 'Kabupaten Sampang', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '35'), '35.28', 'Kabupaten Pamekasan', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '35'), '35.29', 'Kabupaten Sumenep', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '35'), '35.71', 'Kota Kediri', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '35'), '35.72', 'Kota Blitar', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '35'), '35.73', 'Kota Malang', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '35'), '35.74', 'Kota Probolinggo', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '35'), '35.75', 'Kota Pasuruan', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '35'), '35.76', 'Kota Mojokerto', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '35'), '35.77', 'Kota Madiun', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '35'), '35.78', 'Kota Surabaya', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '35'), '35.79', 'Kota Batu', -7.832720, 112.537510),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '36'), '36.01', 'Kabupaten Pandeglang', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '36'), '36.02', 'Kabupaten Lebak', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '36'), '36.03', 'Kabupaten Tangerang', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '36'), '36.04', 'Kabupaten Serang', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '36'), '36.71', 'Kota Tangerang', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '36'), '36.72', 'Kota Cilegon', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '36'), '36.73', 'Kota Serang', -6.125630, 106.149990),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '36'), '36.74', 'Kota Tangerang Selatan', -6.293730, 106.712440),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '51'), '51.01', 'Kabupaten Jembrana', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '51'), '51.02', 'Kabupaten Tabanan', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '51'), '51.03', 'Kabupaten Badung', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '51'), '51.04', 'Kabupaten Gianyar', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '51'), '51.05', 'Kabupaten Klungkung', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '51'), '51.06', 'Kabupaten Bangli', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '51'), '51.07', 'Kabupaten Karangasem', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '51'), '51.08', 'Kabupaten Buleleng', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '51'), '51.71', 'Kota Denpasar', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '52'), '52.01', 'Kabupaten Lombok Barat', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '52'), '52.02', 'Kabupaten Lombok Tengah', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '52'), '52.03', 'Kabupaten Lombok Timur', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '52'), '52.04', 'Kabupaten Sumbawa', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '52'), '52.05', 'Kabupaten Dompu', -8.509400, 118.481600),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '52'), '52.06', 'Kabupaten Bima', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '52'), '52.07', 'Kabupaten Sumbawa Barat', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '52'), '52.08', 'Kabupaten Lombok Utara', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '52'), '52.71', 'Kota Mataram', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '52'), '52.72', 'Kota Bima', -8.467280, 118.752590),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '53'), '53.01', 'Kabupaten Kupang', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '53'), '53.02', 'Kabupaten Timor Tengah Selatan', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '53'), '53.03', 'Kabupaten Timor Tengah Utara', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '53'), '53.04', 'Kabupaten Belu', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '53'), '53.05', 'Kabupaten Alor', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '53'), '53.06', 'Kabupaten Flores Timur', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '53'), '53.07', 'Kabupaten Sikka', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '53'), '53.08', 'Kabupaten Ende', -8.840560, 121.663890),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '53'), '53.09', 'Kabupaten Ngada', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '53'), '53.10', 'Kabupaten Manggarai', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '53'), '53.11', 'Kabupaten Sumba Timur', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '53'), '53.12', 'Kabupaten Sumba Barat', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '53'), '53.13', 'Kabupaten Lembata', -8.413960, 123.552250),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '53'), '53.14', 'Kabupaten Rote Ndao', -10.736170, 123.120540),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '53'), '53.15', 'Kabupaten Manggarai Barat', -8.644840, 119.882810),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '53'), '53.16', 'Kabupaten Nagekeo', -8.872100, 121.209630),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '53'), '53.17', 'Kabupaten Sumba Tengah', -9.629410, 119.619140),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '53'), '53.18', 'Kabupaten Sumba Barat Daya', -9.562160, 119.089050),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '53'), '53.19', 'Kabupaten Manggarai Timur', -8.555330, 120.597610),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '53'), '53.20', 'Kabupaten Sabu Raijua', -10.562860, 121.788940),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '53'), '53.21', 'Kabupaten Malaka', -9.563200, 124.894810),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '53'), '53.71', 'Kota Kupang', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '61'), '61.01', 'Kabupaten Sambas', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '61'), '61.02', 'Kabupaten Mempawah', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '61'), '61.03', 'Kabupaten Sanggau', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '61'), '61.04', 'Kabupaten Ketapang', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '61'), '61.05', 'Kabupaten Sintang', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '61'), '61.06', 'Kabupaten Kapuas Hulu', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '61'), '61.07', 'Kabupaten Bengkayang', 1.069110, 109.663930),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '61'), '61.08', 'Kabupaten Landak', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '61'), '61.09', 'Kabupaten Sekadau', 0.034850, 110.950660),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '61'), '61.10', 'Kabupaten Melawi', -0.336170, 111.698000),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '61'), '61.11', 'Kabupaten Kayong Utara', -1.060230, 110.104020),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '61'), '61.12', 'Kabupaten Kubu Raya', -0.319240, 109.518650),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '61'), '61.71', 'Kota Pontianak', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '61'), '61.72', 'Kota Singkawang', 0.907340, 109.001030),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '62'), '62.01', 'Kabupaten Kotawaringin Barat', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '62'), '62.02', 'Kabupaten Kotawaringin Timur', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '62'), '62.03', 'Kabupaten Kapuas', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '62'), '62.04', 'Kabupaten Barito Selatan', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '62'), '62.05', 'Kabupaten Barito Utara', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '62'), '62.06', 'Kabupaten Katingan', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '62'), '62.07', 'Kabupaten Seruyan', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '62'), '62.08', 'Kabupaten Sukamara', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '62'), '62.09', 'Kabupaten Lamandau', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '62'), '62.10', 'Kabupaten Gunung Mas', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '62'), '62.11', 'Kabupaten Pulang Pisau', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '62'), '62.12', 'Kabupaten Murung Raya', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '62'), '62.13', 'Kabupaten Barito Timur', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '62'), '62.71', 'Kota Palangkaraya', -1.769790, 113.731260),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '63'), '63.01', 'Kabupaten Tanah Laut', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '63'), '63.02', 'Kabupaten Kotabaru', -2.766670, 116.000000),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '63'), '63.03', 'Kabupaten Banjar', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '63'), '63.04', 'Kabupaten Barito Kuala', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '63'), '63.05', 'Kabupaten Tapin', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '63'), '63.06', 'Kabupaten Hulu Sungai Selatan', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '63'), '63.07', 'Kabupaten Hulu Sungai Tengah', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '63'), '63.08', 'Kabupaten Hulu Sungai Utara', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '63'), '63.09', 'Kabupaten Tabalong', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '63'), '63.10', 'Kabupaten Tanah Bumbu', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '63'), '63.11', 'Kabupaten Balangan', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '63'), '63.71', 'Kota Banjarmasin', -3.324440, 114.591020),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '63'), '63.72', 'Kota Banjarbaru', -3.483040, 114.811620),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '64'), '64.01', 'Kabupaten Paser', -1.435170, 116.235350),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '64'), '64.02', 'Kabupaten Kutai Kartanegara', -0.440190, 116.981390),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '64'), '64.03', 'Kabupaten Berau', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '64'), '64.07', 'Kabupaten Kutai Barat', -0.594170, 115.515750),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '64'), '64.08', 'Kabupaten Kutai Timur', 1.037690, 117.831120),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '64'), '64.09', 'Kabupaten Penajam Paser Utara', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '64'), '64.11', 'Kabupaten Mahakam Ulu', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '64'), '64.71', 'Kota Balikpapan', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '64'), '64.72', 'Kota Samarinda', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '64'), '64.74', 'Kota Bontang', 0.125260, 117.496030),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '65'), '65.01', 'Kabupaten Bulungan', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '65'), '65.02', 'Kabupaten Malinau', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '65'), '65.03', 'Kabupaten Nunukan', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '65'), '65.04', 'Kabupaten Tana Tidung', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '65'), '65.71', 'Kota Tarakan', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '71'), '71.01', 'Kabupaten Bolaang Mongondow', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '71'), '71.02', 'Kabupaten Minahasa', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '71'), '71.03', 'Kabupaten Kepulauan Sangihe', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '71'), '71.04', 'Kabupaten Kepulauan Talaud', 4.311780, 126.780850),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '71'), '71.05', 'Kabupaten Minahasa Selatan', 1.212910, 124.597080),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '71'), '71.06', 'Kabupaten Minahasa Utara', 1.402500, 124.960000),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '71'), '71.07', 'Kabupaten Minahasa Tenggara', 1.056330, 124.792500),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '71'), '71.08', 'Kabupaten Bolaang Mongondow Utara', 0.785270, 123.417660),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '71'), '71.09', 'Kabupaten Kepulauan Siau Tagulandang Biaro', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '71'), '71.10', 'Kabupaten Bolaang Mongondow Timur', 0.720730, 124.502560),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '71'), '71.11', 'Kabupaten Bolaang Mongondow Selatan', 0.409120, 123.759610),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '71'), '71.71', 'Kota Manado', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '71'), '71.72', 'Kota Bitung', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '71'), '71.73', 'Kota Tomohon', 1.313070, 124.834040),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '71'), '71.74', 'Kota Kotamobagu', 0.689150, 124.326780),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '72'), '72.01', 'Kabupaten Banggai', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '72'), '72.02', 'Kabupaten Poso', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '72'), '72.03', 'Kabupaten Donggala', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '72'), '72.04', 'Kabupaten Toli-Toli', 1.308620, 120.886430),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '72'), '72.05', 'Kabupaten Buol', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '72'), '72.06', 'Kabupaten Morowali', -2.760620, 121.952670),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '72'), '72.07', 'Kabupaten Banggai Kepulauan', -1.302360, 123.037260),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '72'), '72.08', 'Kabupaten Parigi Moutong', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '72'), '72.09', 'Kabupaten Tojo Una Una', -1.203600, 121.482010),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '72'), '72.10', 'Kabupaten Sigi', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '72'), '72.11', 'Kabupaten Banggai Laut', -1.618410, 123.493880),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '72'), '72.12', 'Kabupaten Morowali Utara', -1.720700, 121.246490),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '72'), '72.71', 'Kota Palu', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '73'), '73.01', 'Kabupaten Kepulauan Selayar', -6.816670, 120.800000),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '73'), '73.02', 'Kabupaten Bulukumba', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '73'), '73.03', 'Kabupaten Bantaeng', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '73'), '73.04', 'Kabupaten Jeneponto', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '73'), '73.05', 'Kabupaten Takalar', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '73'), '73.06', 'Kabupaten Gowa', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '73'), '73.07', 'Kabupaten Sinjai', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '73'), '73.08', 'Kabupaten Bone', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '73'), '73.09', 'Kabupaten Maros', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '73'), '73.10', 'Kabupaten Pangkajene dan Kepulauan', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '73'), '73.11', 'Kabupaten Barru', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '73'), '73.12', 'Kabupaten Soppeng', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '73'), '73.13', 'Kabupaten Wajo', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '73'), '73.14', 'Kabupaten Sidenreng Rappang', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '73'), '73.15', 'Kabupaten Pinrang', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '73'), '73.16', 'Kabupaten Enrekang', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '73'), '73.17', 'Kabupaten Luwu', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '73'), '73.18', 'Kabupaten Tana Toraja', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '73'), '73.22', 'Kabupaten Luwu Utara', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '73'), '73.24', 'Kabupaten Luwu Timur', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '73'), '73.26', 'Kabupaten Toraja Utara', -2.927380, 119.792180),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '73'), '73.71', 'Kota Makassar', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '73'), '73.72', 'Kota Parepare', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '73'), '73.73', 'Kota Palopo', -2.978410, 120.110780),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '74'), '74.01', 'Kabupaten Kolaka', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '74'), '74.02', 'Kabupaten Konawe', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '74'), '74.03', 'Kabupaten Muna', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '74'), '74.04', 'Kabupaten Buton', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '74'), '74.05', 'Kabupaten Konawe Selatan', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '74'), '74.06', 'Kabupaten Bombana', -4.625700, 121.816410),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '74'), '74.07', 'Kabupaten Wakatobi', -5.319340, 123.594800),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '74'), '74.08', 'Kabupaten Kolaka Utara', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '74'), '74.09', 'Kabupaten Konawe Utara', -3.415520, 121.990810),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '74'), '74.10', 'Kabupaten Buton Utara', -5.014570, 122.930150),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '74'), '74.11', 'Kabupaten Kolaka Timur', -4.018070, 121.861720),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '74'), '74.12', 'Kabupaten Konawe Kepulauan', -4.116560, 123.101810),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '74'), '74.13', 'Kabupaten Muna Barat', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '74'), '74.14', 'Kabupaten Buton Tengah', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '74'), '74.15', 'Kabupaten Buton Selatan', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '74'), '74.71', 'Kota Kendari', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '74'), '74.72', 'Kota Bau Bau', -5.477000, 122.616600),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '75'), '75.01', 'Kabupaten Gorontalo', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '75'), '75.02', 'Kabupaten Boalemo', 0.626890, 122.356800),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '75'), '75.03', 'Kabupaten Bone Bolango', 0.502960, 123.275010),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '75'), '75.04', 'Kabupaten Pohuwato', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '75'), '75.05', 'Kabupaten Gorontalo Utara', 0.865080, 123.048910),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '75'), '75.71', 'Kota Gorontalo', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '76'), '76.01', 'Kabupaten Pasangkayu', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '76'), '76.02', 'Kabupaten Mamuju', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '76'), '76.03', 'Kabupaten Mamasa', -2.964920, 119.306310),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '76'), '76.04', 'Kabupaten Polewali Mandar', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '76'), '76.05', 'Kabupaten Majene', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '76'), '76.06', 'Kabupaten Mamuju Tengah', -2.021600, 119.540540),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '81'), '81.01', 'Kabupaten Maluku Tengah', -3.291670, 128.967500),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '81'), '81.02', 'Kabupaten Maluku Tenggara', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '81'), '81.03', 'Kabupaten Kepulauan Tanimbar', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '81'), '81.04', 'Kabupaten Buru', -3.327670, 126.684130),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '81'), '81.05', 'Kabupaten Seram Bagian Timur', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '81'), '81.06', 'Kabupaten Seram Bagian Barat', -3.102700, 128.429960),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '81'), '81.07', 'Kabupaten Kepulauan Aru', -6.170590, 134.469910),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '81'), '81.08', 'Kabupaten Maluku Barat Daya', -7.829600, 126.173860),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '81'), '81.09', 'Kabupaten Buru Selatan', -3.521870, 126.592710),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '81'), '81.71', 'Kota Ambon', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '81'), '81.72', 'Kota Tual', -5.643010, 132.749350),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '82'), '82.01', 'Kabupaten Halmahera Barat', 1.417090, 127.552640),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '82'), '82.02', 'Kabupaten Halmahera Tengah', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '82'), '82.03', 'Kabupaten Halmahera Utara', 1.731940, 128.007780),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '82'), '82.04', 'Kabupaten Halmahera Selatan', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '82'), '82.05', 'Kabupaten Kepulauan Sula', -1.864600, 125.690460),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '82'), '82.06', 'Kabupaten Halmahera Timur', 1.335170, 128.486270),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '82'), '82.07', 'Kabupaten Pulau Morotai', 2.199240, 128.405460),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '82'), '82.08', 'Kabupaten Pulau Taliabu', -1.845780, 124.789920),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '82'), '82.71', 'Kota Ternate', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '82'), '82.72', 'Kota Tidore Kepulauan', 0.609620, 127.569810),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '91'), '91.03', 'Kabupaten Jayapura', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '91'), '91.05', 'Kabupaten Kepulauan Yapen', -1.787730, 136.277160),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '91'), '91.06', 'Kabupaten Biak Numfor', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '91'), '91.10', 'Kabupaten Sarmi', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '91'), '91.11', 'Kabupaten Keerom', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '91'), '91.15', 'Kabupaten Waropen', -2.730080, 136.645680),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '91'), '91.19', 'Kabupaten Supiori', -0.738810, 135.611110),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '91'), '91.20', 'Kabupaten Mamberamo Raya', -2.235610, 137.782290),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '91'), '91.71', 'Kota Jayapura', -2.646470, 140.777790),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '92'), '92.02', 'Kabupaten Manokwari', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '92'), '92.03', 'Kabupaten Fak Fak', -2.926410, 132.296080),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '92'), '92.06', 'Kabupaten Teluk Bintuni', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '92'), '92.07', 'Kabupaten Teluk Wondama', -2.700000, 134.500000),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '92'), '92.08', 'Kabupaten Kaimana', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '92'), '92.11', 'Kabupaten Manokwari Selatan', -1.605320, 134.003130),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '92'), '92.12', 'Kabupaten Pegunungan Arfak', -1.202560, 133.706510),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '93'), '93.01', 'Kabupaten Merauke', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '93'), '93.02', 'Kabupaten Boven Digoel', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '93'), '93.03', 'Kabupaten Mappi', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '93'), '93.04', 'Kabupaten Asmat', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '94'), '94.01', 'Kabupaten Nabire', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '94'), '94.02', 'Kabupaten Puncak Jaya', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '94'), '94.03', 'Kabupaten Paniai', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '94'), '94.04', 'Kabupaten Mimika', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '94'), '94.05', 'Kabupaten Puncak', -3.561040, 137.319340),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '94'), '94.06', 'Kabupaten Dogiyai', -4.031860, 135.439450),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '94'), '94.07', 'Kabupaten Intan Jaya', -3.410160, 136.708370),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '94'), '94.08', 'Kabupaten Deiyai', -4.152870, 136.405670),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '95'), '95.01', 'Kabupaten Jayawijaya', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '95'), '95.02', 'Kabupaten Pegunungan Bintang', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '95'), '95.03', 'Kabupaten Yahukimo', -4.604030, 139.584050),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '95'), '95.04', 'Kabupaten Tolikara', -3.487990, 138.400390),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '95'), '95.05', 'Kabupaten Mamberamo Tengah', -3.627330, 139.064830),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '95'), '95.06', 'Kabupaten Yalimo', -3.788050, 139.421830),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '95'), '95.07', 'Kabupaten Lanny Jaya', -3.912440, 138.287660),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '95'), '95.08', 'Kabupaten Nduga', -4.450930, 138.100890),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '96'), '96.01', 'Kabupaten Sorong', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '96'), '96.02', 'Kabupaten Sorong Selatan', -1.504950, 132.286380),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '96'), '96.03', 'Kabupaten Raja Ampat', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '96'), '96.04', 'Kabupaten Tambrauw', NULL, NULL),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '96'), '96.05', 'Kabupaten Maybrat', -1.215500, 132.350920),
  ((SELECT id FROM countries WHERE iso_code = 'ID'), (SELECT id FROM provinces WHERE code = '96'), '96.71', 'Kota Sorong', -0.865070, 131.251520)
ON DUPLICATE KEY UPDATE name=VALUES(name), latitude=VALUES(latitude), longitude=VALUES(longitude);
