{
 "title": "Adatrack SLO Dashboard",
 "panels": [
  {
   "title": "Dummy Active Users (Simulation)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "expr": "time() % 5000" }
   ]
  },
  {
   "title": "Postgres Memory Usage (Live)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"adatrack_postgres_local\"}",
     "legendFormat": "Memory (Bytes)"
    }
   ]
  },
  {
   "title": "Node CPU Load (Live)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "targets": [
    { "expr": "node_load1" }
   ]
  },
  {
   "title": "NATS Message Broker CPU (Live)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 6 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=\"adatrack_nats_local\"}[1m])",
     "legendFormat": "CPU Cores"
    }
   ]
  }
 ]
}